name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "dhruvsharma5947@gmail.com"
          git config --global user.name "Dhruv3812"
          git remote add hf https://huggingface.co/spaces/Dhruv3812/S_V_M_Space_for_practice
          git push --force https://<your-hf-username>:$HF_TOKEN@huggingface.co/spaces/Dhruv3812/S_V_M_Space_for_practice
